'use client';

import { useState, useEffect } from 'react';
import { usePublicClient, useWalletClient } from 'wagmi';
import { parseAbi, Address } from 'viem';
import LoadingSpinner from './LoadingSpinner';
import AnimatedNumber, { AnimatedPercentage } from './AnimatedNumber';

// Contract ABI (simplified to avoid tuple parsing issues)
const VERITAS_ABI = parseAbi([
  'function strategyStatus(bytes32) external view returns (uint8)',
  'function getAttestationCount(bytes32) external view returns (uint256)'
]);

interface Strategy {
  user: Address;
  fromContract: Address;
  fromToken: Address;
  amount: bigint;
  toContract: Address;
  callData: `0x${string}`;
  minOutput: bigint;
  deadline: bigint;
}

interface Attestation {
  simulatedGasCost: bigint;
  simulatedOutput: bigint;
  isSafe: boolean;
}

interface StrategyCardProps {
  title: string;
  description: string;
  fromProtocol: string;
  toProtocol: string;
  estimatedAPY: number;
  riskLevel: 'low' | 'medium' | 'high';
  onExecute: () => void;
}

const VERITAS_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_VERITAS_CONTRACT as Address || '0x0000000000000000000000000000000000000000' as Address;

export default function StrategyVerificationAVS() {
  const [selectedStrategy, setSelectedStrategy] = useState<Strategy | null>(null);
  const [strategyHash, setStrategyHash] = useState<`0x${string}` | null>(null);
  const [status, setStatus] = useState<'idle' | 'submitting' | 'waiting' | 'verified' | 'executing' | 'executed'>('idle');
  const [attestation, setAttestation] = useState<Attestation | null>(null);
  const [attestationCount, setAttestationCount] = useState(0);
  const [error, setError] = useState<string | null>(null);

  const publicClient = usePublicClient();
  const { data: walletClient } = useWalletClient();

  // Example strategies generated by AI
  const exampleStrategies: StrategyCardProps[] = [
    {
      title: 'Aave → Pendle Yield Strategy',
      description: 'Move weETH from Aave to Pendle for higher yield. Swap aTokens for PT-weETH',
      fromProtocol: 'Aave V3',
      toProtocol: 'Pendle',
      estimatedAPY: 12.5,
      riskLevel: 'medium',
      onExecute: () => prepareAaveToPendleStrategy()
    },
    {
      title: 'Compound → Morpho Optimization',
      description: 'Migrate position from Compound to Morpho Blue for better rates',
      fromProtocol: 'Compound V3',
      toProtocol: 'Morpho Blue',
      estimatedAPY: 8.3,
      riskLevel: 'low',
      onExecute: () => prepareCompoundToMorphoStrategy()
    },
    {
      title: 'Curve → Convex Boost',
      description: 'Stake Curve LP tokens in Convex for boosted CRV and CVX rewards',
      fromProtocol: 'Curve',
      toProtocol: 'Convex',
      estimatedAPY: 15.7,
      riskLevel: 'medium',
      onExecute: () => prepareCurveToConvexStrategy()
    }
  ];

  // Prepare strategies (simplified - in production, AI would generate these)
  const prepareAaveToPendleStrategy = async () => {
    if (!walletClient) return;

    const strategy: Strategy = {
      user: walletClient.account.address,
      fromContract: '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2' as Address, // Aave V3 Pool
      fromToken: '0xCd5fE23C85820F7B72D0926FC9b05b43E359b7ee' as Address, // weETH
      amount: BigInt('1000000000000000000'), // 1 weETH
      toContract: '0x00000000005BBB0EF59571E58418F9a4357b68A0' as Address, // Pendle Router
      callData: '0x' as `0x${string}`, // Generated by AI
      minOutput: BigInt('900000000000000000'), // 0.9 PT-weETH (10% slippage)
      deadline: BigInt(Math.floor(Date.now() / 1000) + 3600) // 1 hour
    };

    setSelectedStrategy(strategy);
    setStatus('idle');
    setError(null);
  };

  const prepareCompoundToMorphoStrategy = async () => {
    if (!walletClient) return;

    const strategy: Strategy = {
      user: walletClient.account.address,
      fromContract: '0xc3d688B66703497DAA19211EEdff47f25384cdc3' as Address, // Compound V3
      fromToken: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48' as Address, // USDC
      amount: BigInt('1000000000'), // 1000 USDC
      toContract: '0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb' as Address, // Morpho Blue
      callData: '0x' as `0x${string}`,
      minOutput: BigInt('995000000'), // 995 USDC
      deadline: BigInt(Math.floor(Date.now() / 1000) + 3600)
    };

    setSelectedStrategy(strategy);
    setStatus('idle');
    setError(null);
  };

  const prepareCurveToConvexStrategy = async () => {
    if (!walletClient) return;

    const strategy: Strategy = {
      user: walletClient.account.address,
      fromContract: '0xDC24316b9AE028F1497c275EB9192a3Ea0f67022' as Address, // Curve stETH pool
      fromToken: '0x06325440D014e39736583c165C2963BA99fAf14E' as Address, // Curve LP token
      amount: BigInt('10000000000000000000'), // 10 LP tokens
      toContract: '0xF403C135812408BFbE8713b5A23a04b3D48AAE31' as Address, // Convex Booster
      callData: '0x' as `0x${string}`,
      minOutput: BigInt('9500000000000000000'),
      deadline: BigInt(Math.floor(Date.now() / 1000) + 3600)
    };

    setSelectedStrategy(strategy);
    setStatus('idle');
    setError(null);
  };

  // Submit strategy to AVS
  const submitStrategy = async () => {
    if (!selectedStrategy || !walletClient || !publicClient) return;

    try {
      setStatus('submitting');
      setError(null);

      // Submit to contract
      const hash = await walletClient.writeContract({
        address: VERITAS_CONTRACT_ADDRESS,
        abi: VERITAS_ABI,
        functionName: 'submitNewStrategy',
        args: [selectedStrategy]
      });

      console.log('Strategy submitted:', hash);

      // Wait for confirmation
      await publicClient.waitForTransactionReceipt({ hash });

      // Get strategy hash
      const stratHash = await publicClient.readContract({
        address: VERITAS_CONTRACT_ADDRESS,
        abi: VERITAS_ABI,
        functionName: 'getStrategyHash',
        args: [selectedStrategy]
      }) as `0x${string}`;

      setStrategyHash(stratHash);
      setStatus('waiting');

      // Start polling for verification
      pollForVerification(stratHash);
    } catch (err: any) {
      console.error('Submit error:', err);
      setError(err.message || 'Failed to submit strategy');
      setStatus('idle');
    }
  };

  // Poll for strategy verification
  const pollForVerification = async (hash: `0x${string}`) => {
    if (!publicClient) return;

    const pollInterval = setInterval(async () => {
      try {
        const stratStatus = await publicClient.readContract({
          address: VERITAS_CONTRACT_ADDRESS,
          abi: VERITAS_ABI,
          functionName: 'strategyStatus',
          args: [hash]
        }) as number;

        const count = await publicClient.readContract({
          address: VERITAS_CONTRACT_ADDRESS,
          abi: VERITAS_ABI,
          functionName: 'getAttestationCount',
          args: [hash]
        }) as bigint;

        setAttestationCount(Number(count));

        if (stratStatus === 1) { // Verified
          clearInterval(pollInterval);

          const att = await publicClient.readContract({
            address: VERITAS_CONTRACT_ADDRESS,
            abi: VERITAS_ABI,
            functionName: 'getAttestation',
            args: [hash]
          }) as Attestation;

          setAttestation(att);
          setStatus('verified');
        }
      } catch (err) {
        console.error('Poll error:', err);
      }
    }, 3000); // Poll every 3 seconds

    // Timeout after 5 minutes
    setTimeout(() => {
      clearInterval(pollInterval);
      if (status === 'waiting') {
        setError('Verification timeout - operators may be offline');
      }
    }, 300000);
  };

  // Execute verified strategy
  const executeStrategy = async () => {
    if (!selectedStrategy || !walletClient || !publicClient || !strategyHash) return;

    try {
      setStatus('executing');
      setError(null);

      // Step 1: Approve token
      const approveAbi = parseAbi(['function approve(address spender, uint256 amount) external returns (bool)']);

      const approveTx = await walletClient.writeContract({
        address: selectedStrategy.fromToken,
        abi: approveAbi,
        functionName: 'approve',
        args: [VERITAS_CONTRACT_ADDRESS, selectedStrategy.amount]
      });

      await publicClient.waitForTransactionReceipt({ hash: approveTx });

      // Step 2: Execute strategy
      const executeTx = await walletClient.writeContract({
        address: VERITAS_CONTRACT_ADDRESS,
        abi: VERITAS_ABI,
        functionName: 'executeVerifiedStrategy',
        args: [selectedStrategy]
      });

      await publicClient.waitForTransactionReceipt({ hash: executeTx });

      setStatus('executed');
    } catch (err: any) {
      console.error('Execute error:', err);
      setError(err.message || 'Failed to execute strategy');
      setStatus('verified');
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'low': return 'bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-400';
      case 'medium': return 'bg-yellow-50 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-400';
      case 'high': return 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400';
      default: return 'bg-gray-50 dark:bg-gray-900/20 text-gray-700 dark:text-gray-400';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="handcrafted-card rounded-3xl p-8 soft-glow accent-line">
        <div className="ml-8">
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-3">
            <span className="text-3xl">🛡️</span>
            <span className="hand-underline">Veritas AVS - Strategy Verification</span>
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-6">
            Submit your DeFi strategies for operator verification before execution. Multi-operator consensus ensures safety.
          </p>

          <div className="grid grid-cols-3 gap-4">
            <div className="bg-gradient-to-br from-emerald-50 to-cyan-50 dark:from-emerald-900/20 dark:to-cyan-900/20 rounded-xl p-4">
              <p className="text-xs text-gray-600 dark:text-gray-400 mb-1">Network Operators</p>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">12</p>
            </div>
            <div className="bg-gradient-to-br from-violet-50 to-purple-50 dark:from-violet-900/20 dark:to-purple-900/20 rounded-xl p-4">
              <p className="text-xs text-gray-600 dark:text-gray-400 mb-1">Verified Today</p>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">47</p>
            </div>
            <div className="bg-gradient-to-br from-amber-50 to-orange-50 dark:from-amber-900/20 dark:to-orange-900/20 rounded-xl p-4">
              <p className="text-xs text-gray-600 dark:text-gray-400 mb-1">Success Rate</p>
              <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">
                <AnimatedPercentage value={98.5} />
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Strategy Selection */}
      {!selectedStrategy && (
        <div className="grid md:grid-cols-3 gap-4">
          {exampleStrategies.map((strat, idx) => (
            <div
              key={idx}
              className="handcrafted-card rounded-2xl p-6 hover:scale-[1.02] transition-all cursor-pointer"
              onClick={strat.onExecute}
            >
              <h4 className="font-bold text-lg text-gray-900 dark:text-white mb-2">
                {strat.title}
              </h4>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
                {strat.description}
              </p>

              <div className="flex items-center justify-between mb-3">
                <span className="text-xs text-gray-500 dark:text-gray-500">{strat.fromProtocol}</span>
                <span className="text-lg">→</span>
                <span className="text-xs text-gray-500 dark:text-gray-500">{strat.toProtocol}</span>
              </div>

              <div className="flex items-center justify-between">
                <span className={`px-2 py-1 rounded-full text-xs font-semibold ${getRiskColor(strat.riskLevel)}`}>
                  {strat.riskLevel} risk
                </span>
                <span className="text-lg font-bold text-emerald-600 dark:text-emerald-400">
                  <AnimatedPercentage value={strat.estimatedAPY} />
                </span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Strategy Workflow */}
      {selectedStrategy && (
        <div className="handcrafted-card rounded-3xl p-8">
          <h4 className="font-bold text-xl text-gray-900 dark:text-white mb-6">
            Strategy Verification Workflow
          </h4>

          {/* Progress Steps */}
          <div className="flex items-center justify-between mb-8">
            {['Submit', 'Verify', 'Execute'].map((step, idx) => (
              <div key={idx} className="flex items-center">
                <div className={`w-12 h-12 rounded-full flex items-center justify-center font-bold text-lg ${
                  idx === 0 && status !== 'idle' ? 'bg-emerald-500 text-white' :
                  idx === 1 && (status === 'waiting' || status === 'verified' || status === 'executing' || status === 'executed') ? 'bg-emerald-500 text-white' :
                  idx === 2 && (status === 'executing' || status === 'executed') ? 'bg-emerald-500 text-white' :
                  'bg-gray-200 dark:bg-gray-700 text-gray-600 dark:text-gray-400'
                }`}>
                  {idx + 1}
                </div>
                <span className="ml-3 font-semibold text-gray-900 dark:text-white">{step}</span>
                {idx < 2 && <div className="w-20 h-1 mx-4 bg-gray-200 dark:bg-gray-700" />}
              </div>
            ))}
          </div>

          {/* Status Display */}
          {status === 'idle' && (
            <div className="text-center py-8">
              <button
                onClick={submitStrategy}
                disabled={!walletClient}
                className="px-8 py-4 bg-gradient-to-r from-emerald-600 to-cyan-600 text-white font-bold text-lg rounded-xl hover:from-emerald-700 hover:to-cyan-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                Submit for Verification
              </button>
            </div>
          )}

          {status === 'submitting' && (
            <div className="text-center py-8">
              <LoadingSpinner size="lg" text="Submitting strategy to AVS..." />
            </div>
          )}

          {status === 'waiting' && (
            <div className="text-center py-8">
              <LoadingSpinner size="lg" text="Waiting for operator verification..." />
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-4">
                Attestations received: {attestationCount} / 5
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-500 mt-2">
                Operators are simulating your strategy and analyzing safety...
              </p>
            </div>
          )}

          {status === 'verified' && attestation && (
            <div className="space-y-6">
              <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-xl p-6">
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-3xl">✅</span>
                  <h5 className="text-lg font-bold text-green-900 dark:text-green-300">
                    Strategy Verified by Operators!
                  </h5>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Simulated Gas Cost</p>
                    <p className="text-lg font-bold text-gray-900 dark:text-white">
                      <AnimatedNumber value={Number(attestation.simulatedGasCost)} decimals={0} /> gas
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Expected Output</p>
                    <p className="text-lg font-bold text-gray-900 dark:text-white">
                      {(Number(attestation.simulatedOutput) / 1e18).toFixed(4)} tokens
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">AI Safety Check</p>
                    <p className={`text-lg font-bold ${attestation.isSafe ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                      {attestation.isSafe ? '✓ Safe' : '✗ Unsafe'}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Operator Consensus</p>
                    <p className="text-lg font-bold text-emerald-600 dark:text-emerald-400">
                      {attestationCount} operators
                    </p>
                  </div>
                </div>
              </div>

              <div className="text-center">
                <button
                  onClick={executeStrategy}
                  disabled={!attestation.isSafe}
                  className="px-8 py-4 bg-gradient-to-r from-violet-600 to-purple-600 text-white font-bold text-lg rounded-xl hover:from-violet-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                  Execute Strategy
                </button>
                {!attestation.isSafe && (
                  <p className="text-sm text-red-600 dark:text-red-400 mt-2">
                    Strategy marked unsafe by operators - execution disabled
                  </p>
                )}
              </div>
            </div>
          )}

          {status === 'executing' && (
            <div className="text-center py-8">
              <LoadingSpinner size="lg" text="Executing strategy..." />
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-4">
                Step 1: Approving tokens...
              </p>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">
                Step 2: Executing on-chain...
              </p>
            </div>
          )}

          {status === 'executed' && (
            <div className="text-center py-8">
              <div className="text-6xl mb-4">🎉</div>
              <h5 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                Strategy Executed Successfully!
              </h5>
              <p className="text-gray-600 dark:text-gray-400">
                Your DeFi strategy has been safely executed with operator verification
              </p>
              <button
                onClick={() => {
                  setSelectedStrategy(null);
                  setStatus('idle');
                  setAttestation(null);
                  setAttestationCount(0);
                }}
                className="mt-6 px-6 py-3 bg-gray-600 text-white font-semibold rounded-xl hover:bg-gray-700 transition-all"
              >
                Back to Strategies
              </button>
            </div>
          )}

          {error && (
            <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl p-4">
              <p className="text-red-800 dark:text-red-400">❌ {error}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
